import ROICalculatorTemplate from '../../components/ROICalculatorTemplate';

export default function MarketingROICalculator() {
  const fields = [
    {
      id: 'monthlyAdSpend',
      label: 'Monthly Advertising Spend',
      type: 'number' as const,
      placeholder: '10000',
      prefix: '$',
      defaultValue: 10000
    },
    {
      id: 'marketingTeamSize',
      label: 'Marketing Team Size',
      type: 'number' as const,
      placeholder: '5',
      defaultValue: 5
    },
    {
      id: 'avgMarketingSalary',
      label: 'Average Marketing Employee Salary',
      type: 'number' as const,
      placeholder: '70000',
      prefix: '$',
      defaultValue: 70000
    },
    {
      id: 'currentConversionRate',
      label: 'Current Conversion Rate',
      type: 'select' as const,
      options: [
        { value: '1', label: '1% - Below Average' },
        { value: '2.5', label: '2.5% - Industry Average' },
        { value: '5', label: '5% - Above Average' },
        { value: '8', label: '8% - Excellent' }
      ],
      defaultValue: 2.5
    },
    {
      id: 'averageOrderValue',
      label: 'Average Order Value',
      type: 'number' as const,
      placeholder: '150',
      prefix: '$',
      defaultValue: 150
    },
    {
      id: 'aiImprovementRate',
      label: 'AI-Driven Improvement Rate',
      type: 'select' as const,
      options: [
        { value: '0.25', label: '25% - Conservative' },
        { value: '0.40', label: '40% - Moderate' },
        { value: '0.60', label: '60% - Aggressive' },
        { value: '0.80', label: '80% - Best Case' }
      ],
      defaultValue: 0.40
    },
    {
      id: 'aiToolsCost',
      label: 'Monthly AI Marketing Tools Cost',
      type: 'number' as const,
      placeholder: '2000',
      prefix: '$',
      defaultValue: 2000
    }
  ];

  const calculations = [
    {
      id: 'currentRevenue',
      label: 'Current Monthly Revenue',
      formula: (values: Record<string, number>) => {
        const { monthlyAdSpend, currentConversionRate, averageOrderValue } = values;
        const clicks = monthlyAdSpend / 2; // Assume $2 CPC
        const conversions = clicks * (currentConversionRate / 100);
        return conversions * averageOrderValue || 0;
      },
      format: 'currency' as const,
      description: 'Estimated monthly revenue from current marketing efforts'
    },
    {
      id: 'improvedRevenue',
      label: 'Projected Revenue with AI',
      formula: (values: Record<string, number>) => {
        const { monthlyAdSpend, currentConversionRate, averageOrderValue, aiImprovementRate } = values;
        const clicks = monthlyAdSpend / 2;
        const improvedConversionRate = currentConversionRate * (1 + aiImprovementRate);
        const conversions = clicks * (improvedConversionRate / 100);
        return conversions * averageOrderValue || 0;
      },
      format: 'currency' as const,
      description: 'Projected monthly revenue with AI-optimized marketing'
    },
    {
      id: 'monthlyIncrease',
      label: 'Monthly Revenue Increase',
      formula: (values: Record<string, number>) => {
        const { monthlyAdSpend, currentConversionRate, averageOrderValue, aiImprovementRate } = values;
        const clicks = monthlyAdSpend / 2;
        const currentConversions = clicks * (currentConversionRate / 100);
        const improvedConversions = clicks * ((currentConversionRate * (1 + aiImprovementRate)) / 100);
        const currentRevenue = currentConversions * averageOrderValue;
        const improvedRevenue = improvedConversions * averageOrderValue;
        return improvedRevenue - currentRevenue || 0;
      },
      format: 'currency' as const,
      description: 'Additional monthly revenue generated by AI optimization'
    },
    {
      id: 'annualROI',
      label: 'Annual Net ROI',
      formula: (values: Record<string, number>) => {
        const { monthlyAdSpend, currentConversionRate, averageOrderValue, aiImprovementRate, aiToolsCost } = values;
        const clicks = monthlyAdSpend / 2;
        const currentConversions = clicks * (currentConversionRate / 100);
        const improvedConversions = clicks * ((currentConversionRate * (1 + aiImprovementRate)) / 100);
        const monthlyIncrease = (improvedConversions - currentConversions) * averageOrderValue;
        const annualIncrease = monthlyIncrease * 12;
        const annualAICost = aiToolsCost * 12;
        return annualIncrease - annualAICost || 0;
      },
      format: 'currency' as const,
      description: 'Annual return after deducting AI tool costs'
    },
    {
      id: 'roiMultiplier',
      label: 'ROI Multiplier',
      formula: (values: Record<string, number>) => {
        const { monthlyAdSpend, currentConversionRate, averageOrderValue, aiImprovementRate, aiToolsCost } = values;
        const clicks = monthlyAdSpend / 2;
        const currentConversions = clicks * (currentConversionRate / 100);
        const improvedConversions = clicks * ((currentConversionRate * (1 + aiImprovementRate)) / 100);
        const monthlyIncrease = (improvedConversions - currentConversions) * averageOrderValue;
        const annualIncrease = monthlyIncrease * 12;
        const annualAICost = aiToolsCost * 12;
        return annualAICost > 0 ? annualIncrease / annualAICost : 0;
      },
      format: 'number' as const,
      description: 'How many times your investment you get back annually'
    }
  ];

  const benefits = [
    'Increase conversion rates by 25-60%',
    'Improve ad targeting and reduce waste',
    'Automate A/B testing and optimization',
    'Personalize customer experiences at scale',
    'Reduce manual campaign management time',
    'Get real-time insights and recommendations'
  ];

  const caseStudies = [
    {
      company: 'E-commerce Plus',
      industry: 'E-commerce',
      savings: '300% ROI',
      timeframe: '6 months'
    },
    {
      company: 'SaaS Growth Co',
      industry: 'SaaS',
      savings: '450% ROI',
      timeframe: '9 months'
    },
    {
      company: 'Retail Chain',
      industry: 'Retail',
      savings: '220% ROI',
      timeframe: '12 months'
    }
  ];

  return (
    <ROICalculatorTemplate
      title="Marketing AI ROI Calculator"
      description="Calculate the return on investment for AI-powered marketing tools. Estimate increased conversions, revenue growth, and cost savings from marketing automation."
      category="Marketing AI"
      fields={fields}
      calculations={calculations}
      benefits={benefits}
      caseStudies={caseStudies}
    />
  );
}